package com.dev.chacha.resources.strings.ar

import com.dev.chacha.resources.strings.IStringResources

data class Arabic(
    override val appName: String = "EquityMobile",
    override val passwordVisibleContentDescription: String = "Hide password",
    override val passwordHiddenContentDescription: String = "Show password",
    override val dontHaveAnAccountYet: String = "Don't have an account? Please",
    override val signUp: String = "Sign up!",
    override val email: String = "E-Mail",
    override val register: String = "Register",
    override val createYourProfile: String = "Create your profile",
    override val country: String = "Country",
    override val selectCountry: String = "Select a country",
    override val accountNumberHint: String = "Enter an account or mobile number",
    override val accountNumberTitle: String = "Account number",
    override val idNumberHint: String = "Enter your ID number",
    override val idNumberTitle: String = "ID number",
    override val agreeToTermsAndPrivacyPolicy: String = "I agree to the terms and privacy policy",
    override val createProfileAddAccounts: String = "Create profile + add accounts",
    override val welcomeBack: String = "Welcome back",
    override val helloThere: String = "Hello there",
    override val emailHint: String = "Email address or mobile number",
    override val loginPasswordHint: String = "Enter password",
    override val loginPasswordTitle: String = "Password",
    override val forgotPassword: String = "Forgot Password?",
    override val enterPasswordToSignIn: String = "Enter password",
    override val loginHeaderDescription: String = "Sign in to Continue. Remember, your password is yours, do not share it with anyone.",
    override val alreadyHaveAnAccount: String = "Already have an account? Go to the",
    override val signIn: String = "Login Page",
    override val username: String = "Username",
    override val loginHint: String = "Username / E-Mail",
    override val login: String = "Login",
    override val createPinHeader: String = "Create your 4-digit PIN",
    override val createPinHint: String = "Make sure that your PIN is unique and secure",
    override val passwordHint: String = "Enter password",
    override val reEnterPasswordHint: String = "Re-enter your password",
    override val createPassword: String = "Create password",
    override val createPasswdHeader: String = "Create a strong password",
    override val createPasswordHint: String = "The harder the password, the better and safer",
    override val confirmPassword: String = "Confirm Password",
    override val passwordTitle: String = "Password",
    override val validateHeader: String = "What is required?",
    override val validateLetter: String = "Must contain both numbers, uppercase and lowercase letters",
    override val validateCharLong: String = "Must be at least 8 characters long",
    override val validateSpecialChar: String = "Must contain a special character (e.g. !@#$&)",
    override val passwordMatch: String = "Password must match",
    override val pinValidateHeader: String = "How to create a secure PIN:",
    override val validateSequence: String = "Avoid number sequences (e.g. 1234 or 9876)",
    override val validateRepetitive: String = "Avoid using repetitive digits (e.g. 0000, 1111)",
    override val verifyHeader: String = "How would you like to get verified?",
    override val selectHint: String = "Select one of the options below",
    override val greetings: String = "Good evening, Stephen",
    override val homeHint: String = "What would you like to do today?",
    override val purpose1: String = "This loan is available to Equity members who have had their Equity bank account for at least six months",
    override val purpose2: String = "You can borrow up to 1,000,000 KES, while can be paid over a period of 12 months.",
    override val purpose3: String = "How much can I borrow?",
    override val purpose4: String = "You can check your loan limit and find out",
    override val loanDesc: String = "Equity offers a variety of loans to help you meet your goals. Look through our loan products to find one that is suited to your needs",
    override val purpose: String = "Borrow up to 1,000,000 KES and pay back over up to twelve months",
    override val manageDevices: String = "You can remove any of the devices connected to your profile",
    override val getInTouch: String = "Reach out to us anytime you need help and our talented team will be glad to assist you",
    override val favourite: String = "Your favorite contact will appear here. Add a new one to quickly transact",
    override val titleActivityMain: String = "MainActivity",
    override val firstFragmentLabel: String = "First Fragment",
    override val secondFragmentLabel: String = "Second Fragment",
    override val next: String = "Next",
    override val previous: String = "Previous",
    override val changePasswordTitle: String = "Change your password",
    override val changePasswordDescription: String = "Create a new password",
    override val confirmPass: String = "Confirm",
    override val schedulePayment: String = "Schedule payment",
    override val westernUnionHint: String = "Western Union",
    override val paypalHint: String = "PayPal",
    override val addFavorite: String = "Add a favorite",
    override val favorite: String = "Favorite",
    override val ownEquityAccount: String = "Own Equity account",
    override val anotherEquityAccount: String = "Another Equity account",
    override val payTopUp: String = "Pay to card",
    override val creditPrepaid: String = "Credit and prepaid cards",
    override val mobileWallet: String = "Mobile money",
    override val sendToMobile: String = "Send to mobile money providers",
    override val anotherBank: String = "Another Bank",
    override val payBill: String = "Pay bill",
    override val buyAirtime: String = "Buy airtime",
    override val buyGoods: String = "Buy goods",
    override val agent: String = "Agent",
    override val haveYouForgottenYourPassword: String = "Have you forgotten your password",
    override val forgotPasswordDescription: String = "We'll email or text you a link to help you reset your password",
    override val emailOrMobileNumber: String = "Email address or mobile number",
    override val pinTitle: String = "PIN",
    override val pinHint: String = "Enter Pin",
    override val confirmPin: String = "Confirm PIN",
    override val confirmPinHint: String = "Confirm PIN",
    override val setPin: String = "Set PIN",
    override val createDialogDescription: String = "You can now simplify some of your regular transactions with a unique and easy to remember, 4-Digit PIN",
    override val yowOweHint: String = "",
    override val apply: String = "Apply",
    override val selectFinishDateTitle: String = "Select End Date",
    override val today: String = "Today",
    override val notFoundEmail: String = "not found\n",
    override val copyToClipboard: String = "copied to clipboard",
    override val openAccount: String = "Open account",
    override val loans: String = "Loans",
    override val borrow: String = "Borrow",
    override val payLoan: String = "Pay loan",
    override val getLoan: String = "Get loan",
    override val oneMonthLoanTitle: String = "One Month Loan",
    override val oneMonthLoanSubtitle: String = "Borrow up to 1,000,000 KES and pay it back in one month",
    override val installmentLoanTitle: String = "Installment Loan",
    override val installmentLoanSubtitle: String = "Borrow up to 1,000,000 KES and pay it back over up to twelve months",
    override val pensionLoanTitle: String = "Pension Loan",
    override val pensionLoanSubtitle: String = "Loan for members who receive a monthly pension",
    override val salaryAdvanceLoanTitle: String = "Salary Advance Loan",
    override val salaryAdvanceLoanSubtitle: String = "Short-tern loan for members who receive a monthly salary",
    override val ecosystemLoanTitle: String = "EcoSystem Loan",
    override val ecosystemLoanSubtitle: String = "This product is for approved retailers who sell products stocked by a local anchor or sub-anchor",

    // About One Month loan
    override val aboutOneMonthLoan1: String = "This loan is available to Equity members who have had their Equity bank account for at least six months",
    override val aboutOneMonthLoan2: String = "You can borrow up to 1,000,000 KES, which can be paid in 1 month",
    override val aboutOneMonthLoan3: String = "How much can I borrow?",
    override val aboutOneMonthLoan4: String = "You can check your loan limit to find out",

    // About Installment loan
    override val aboutInstallmentLoan1: String = "This loan is available to Equity members who have had their Equity bank account for at least six months",
    override val aboutInstallmentLoan2: String = "You can borrow up to 1,000,000 KES, which can be paid over a period of 12 months",
    override val aboutInstallmentLoan3: String = "How much can I borrow?",
    override val aboutInstallmentLoan4: String = "You can check your loan limit to find out",

    // About pension loan
    override val aboutPensionLoan1: String = "As a pensioner, it is important for you to enjoy your time in retirement while also being able to have everything you need and want. The Pension Loan is designed to help you meet your emergency needs, and is based on your account profile",
    override val aboutPensionLoan2: String = "For this loan, We offer a repayment period of up to 48 months.\n You can qualify for a maximum loan amount of 3,800,000 KES",
    override val aboutPensionLoan3: String = "How much can I borrow?",
    override val aboutPensionLoan4: String = "You can check your loan limit to find out",

    // About Salary Advance loan
    override val aboutSalaryLoan1: String = "This is a short-term loan to help you meet your emergency needs. The loan is based on your profile.",
    override val aboutSalaryLoan2: String = "For this loan, We offer a repayment period of up to 12 months.\n To qualify, your salary must have been coming into your Equity Bank account for at least three months",
    override val aboutSalaryLoan3: String = "You can qualify for a maximum amount of 4 times your monthly salary.",
    override val aboutSalaryLoan4: String = "Any amount exceeding 300,000 KES must be secured with either a log book or title deed.",
    override val aboutSalaryLoan5: String = "How much can I borrow?",
    override val aboutSalaryLoan6: String = "You can check your loan limit to find out",

    // About EcoSystem loan
    override val aboutEcosystemLoan1: String = "This product is for approved retailers who sell products stocked by a local anchor or sub-anchor. Through this facility, retailers can withdraw funds for stock financing requirements, quickly and conveniently, whenever it is needed. ",
    override val aboutEcosystemLoan2: String = "A retailer has the option to insure the goods they order, to cover any loss or damage that can occur while the products are in transit",
    override val aboutEcosystemLoan3: String = "How much can I borrow?\n- A minimum amount of KES\n-A maximum amount of 1,000,000 KES (This depends on the anchor\n- Any amount above 1,000,000 KES should be fully secured",
    override val aboutEcosystemLoan4: String = "Any amount exceeding 300,000 KES must be secured with either a log book or title deed.",
    override val aboutEcosystemLoan5: String = "The ecosystem loan is a revolving stock financing facility. Each drawn will be repaid within the agreed period, which is a maximum of 30 days, depending on the customer segement. The overall loan limit is approved for a 3-month period, which can be renewed based on the review of previous performance",
    override val aboutEcosystemLoan6: String = "How much can I borrow?",
    override val aboutEcosystemLoan7: String = "You can check your loan limit to find out",

    // About Classic savings
    override val aboutClassicSavingsTitle: String = "Classic account",
    override val aboutClassicAccount: String = "Save any amount and deposit as frequently as you can, while earning compounded interest on deposits.",
    override val aboutClassicInterestTitle: String = "Interest rate",
    override val aboutClassicInterestRateDesc1: String = "The interest you'll earn with a Classic savings account is calculated on a simple interest basis. It is based on the amount you deposit into the account and is subject to change.",
    override val aboutClassicAccountRateDesc2: String = "Interest will only be earned for an account balance of above 20,000.00 KES and is credited at the end of the year and/or at account closure.",
    override val aboutClassicInterestInformation: String = "For more information on the interest rate,\nClick here.",
    override val whatShouldYouGetAccount: String = "Why should you get this account?",
    override val whatShouldYouGetClassicAccountDesc: String = "• Deposit funds into the account as often as you would like to.\n• Your savings are easily available on request.\n• Earn a daily annual return.\n• No charges to move money from your savings account to a bank account.",
    override val aboutClassicBonus: String = "Bonus:\n• There are no monthly charges or fees to operate this account.",
    override val whatYouNeedClassicAccount: String = "What you need",
    override val whatYouNeedClassicAccountDesc: String = "All you need is a minimum opening balance of 1,000 KES and an active Equity online profile.",
    override val aboutClassicWithdrawals: String = "Withdrawals:",
    override val aboutClassicWithdrawDesc1: String = "One free withdrawal is allowed per month. A withdrawal charge of 60.00 KES is applied for any subsequent withdrawals within the same month.",
    override val aboutClassicAccountWithdraw3: String = "If your withdrawals leave less than 20,000 KES in the account, you will forfeit any interest earned.",
    override val aboutClassicAccountWithdraw4: String = "With a full withdrawal, the account will be closed and the funds will be transferred to your source account.",

    // About Call Deposit
    override val aboutCallDepositTitle: String = "Call deposit account",
    override val aboutCallDepositDesc: String = "This savings account allows you to deposit a principal amount, earn interest, and access your money anytime.",
    override val aboutCallDepositInterest: String = "Interest rate",
    override val aboutCallDepositInformation: String = "For more information on the interest rate, click here.",
    override val aboutCallBenefit: String = "• During the investment period, interest is accrued daily.\n• No maximum deposit amount.\n• Unlimited account access on mobile and online.\n• Monthly free e-statements.\n• No monthly charges on your account.",
    override val idealAccountCall: String = "This account is ideal if:",
    override val callDepositIdealDesc: String = "• You have disposable income.\n• You're looking for a great way to earn a return on your savings.",
    override val whatYouNeedCallDepositTitle: String = "What you need",
    override val whatYouNeedCallDeposit: String = "You need to be 18 years of age with an active Equity profile and a minimum balance of 50,000 KES. The maximum deposit period is 12 months.",
    override val callDepositTopAndWithdrawTitle: String = "Top up and Withdraw",
    override val callDepositTopAndWithdraw: String = "Top up your account as often as you would like via the available Move money options. Partial withdrawals are allowed. However, if your account is closed, the funds will be transferred to your source account.",
    override val callDepositAccountClosure: String = "Account closure:",
    override val callDepositAccountClosureDesc: String = "You can manually close your account after one full day of the account being opened. Funds will then be transferred to the source account.",

    // About Fixed Deposit
    override val aboutFixedAccount: String = "Fixed deposit account",
    override val aboutFixedAccountDesc: String = "This account is ideal if you're looking for a way to earn a profitable amount of interest on some spare money you have.",
    override val aboutFixedDepositInterest: String = "Interest rate",
    override val aboutFixedDepositDesc: String = "The account earns daily simple interest.",
    override val aboutFixedDepositInformation: String = "For more information on the interest rate,\nClick here.",
    override val aboutFixedShouldYouAccount: String = "Why should you get this account?",
    override val aboutFixedShouldYouThisAccountDesc: String = "• The minimum period for a Fixed deposit is only one month.\n•  The deposit amount and interest rate are fixed during the investment period.\n• At the time of opening this account, you are informed of the interest you will earn.\n• Principal and interest payment is done upon maturity or account closure.\n• KES is supported.\n• No monthly charges.\n• You can choose to reinvest your savings into a new Fixed deposit account at the end of your deposit period.",
    override val aboutWhatDoNeedToOpenHint: String = "What should you get this account?",
    override val aboutWhatDoNeedToOpenDesc: String = "All you need is a minimum opening balance of 50,000 KES and an active Equity online profile.",
    override val fixedWithdrawal: String = "If you withdraw your funds before reaching your selected deposit period, the account will be closed and the accrued interest will be reduced. The funds will then be transferred to your source account.",

    // About Goal savings
    override val aboutGoalSavingsTitle: String = "Goal account",
    override val aboutGoalAccount: String = "This savings account allows you to set a goal, deposit funds, and seamlessly save towards your financial goals.",
    override val goalInterestTitle: String = "Interest rate",
    override val aboutGoalInterestRate: String = "For more information on the interest rate,\nClick here.",
    override val aboutGoalAccountBenefit: String = "Benefits:",
    override val aboutGoalAccountIdeal: String = "This account is ideal if:",
    override val aboutGoalAccountIdealDesc: String = "\n&#8226; You have a regular and stable income.\n&#8226; You have disposable income.\n&#8226; You're looking for a great way to save towards your financial goals.",
    override val aboutGoalAccountWhatYouNeed: String = "What you need",
    override val aboutGoalAccountWhatYouNeedDescription: String = "You need to be 18 years of age with an active Equity profile and a minimum opening balance of 300.00 KES. This account does not have a minimum term length.",
    override val aboutGoalAccountTopUpAndWithdraw: String = "Top up and withdraw",
    override val aboutGoalAccountTopUpAndWithdrawDesc: String = "Top up your account as often as you like with Move money. You can make 1 free withdrawal every 6 months. After that, a withdrawal charge of 60.00 KES is applied.",
    override val aboutGoalAccountAccountClosure: String = "Account closure",
    override val aboutGoalAccountAccountClosureDesc: String = "You can close your account manually at any time. Funds will then be transferred to the source account.",

    // Get in Touch
    override val contactUs: String = "Contact us",
    override val equityContact: String = "+254 763 063000",
    override val emailUs: String = "Email us",
    override val equityEmail: String = "info@equitybank.co.ke",
    override val website: String = "Visit our website",
    override val equityWebsite: String = "https://equitygroupholdings.com/ke/",
    override val twitter: String = "Follow us on Twitter",
    override val equityTwitter: String = "@KeEquityBank",
    override val facebook: String = "Like us on Facebook",
    override val equityFacebook: String = "https://www.facebook.com/KeEquityBank/",
    override val linkedin: String = "Follow us on LinkedIn",
    override val equityLinkedin: String = "Equity Bank Limited",

    // Manage Devices
    override val mobileDevice: String = "Mobile devices",
    override val noOfMobileDevices: String = "% device",
    override val webDevices: String = "Web devices",
    override val webDevicesNo: String = "% devices",
    override val getInTouchDesc: String = "Reach out to us any time you need help and our talented team will gladly assist you",
    override val whichDeviceWouldYouLikeToRemove: String = "Which device would you like to remove?",
    override val mobileDevicesDesc: String = "Choose the device you want to remove. TO connect it again, simply sign in to your profile using that device",
    override val changeYourPin: String = "Change your PIN",
    override val changeYourExistingPin: String = "Change your existing PIN",
    override val resetYourPin: String = "Reset your PIN",
    override val resetYourPinIfYouVeForgottenIt: String = "Reset your PIN if you've forgotten it",
    override val makeSureYourPinEasy: String = "Make sure your PIN is easy to remember",
    override val enterCurrentPin: String = "Enter your current PIN",
    override val enterNewPin: String = "Enter your new PIN",
    override val newPin: String = "New PIN",
    override val currentPin: String = "Current PIN",
    override val confirmNewPassword: String = "Confirm new password",
    override val newPassword: String = "New password",
    override val currentPassword: String = "Current Password",

    // Notifications
    override val selectTheAccountYouWantToGetTransactionAlertFor: String = "Select the account you want to get transaction alert for",
    override val howDoYouWantToReceiveYourAlerts: String = "How do you want to receive your alerts?",
    override val notificationDisabled: String = "Notifications disabled",
    override val smsAlert: String = "SMS alerts",
    override val alertEnabled: String = "Alert enabled",
    override val enableAllAccounts: String = "Enable all accounts",
    override val notificationEnabled: String = "Notifications enabled",
    override val selectTheAccountYouWantToGetRemindersAlertFor: String = "Select the accounts you want to get reminders for",
    override val howDoYouWantToReceiveYourNotification: String = "How do you want to receive your notifications?",
    override val emailNotification: String = "Email",
    override val pushNotification: String = "Push notification",
    override val accountUser: String = "Stephen Chacha Marwa",
    override val accountNumber: String = "123456789",
    override val buyForSomeoneNew: String = "Buy for someone new",
    override val searchForCountry: String = "Search for a country",
    override val getInTouchSubtitle: String = "Email, call or find us on social media",
    override val makePayment: String = "Make Payment",
    override val sendToSomeoneNew: String = "Send to someone new",
    override val enterAnAccountNumber: String = "Enter an account number",
    override val withdrawFromPaypal: String = "Withdraw from PayPal",
    override val withdrawCash: String = "Withdraw cash",
    override val sendMoney: String = "Send money",
    override val westernUnionSendMoneySubtitle: String = "Send money internationally through Western Union",
    override val receiveMoney: String = "Receive Money",
    override val westernUnionReceiveMoneySubtitle: String = "Receive money by entering a Western Union tracking number",
    override val signInWithTouchId: String = "Sign in with Touch ID",
    override val recommend: String = "Recommend",
    override val activateChatBanking: String = "Activate Chat Banking",
    override val activateChatBankingDesc: String = "Transact with Equity's Virtual Assistant",
    override val addAnEquityAccount: String = "Add an Equity account",
    override val addAnEquityAccountDes: String = "An an Equity account to your profile",
    override val addYourPaypalAccountDesc: String = "Link any two PayPal accounts to your bank accounts",
    override val darkMode: String = "Dark mode",
    override val applyNow: String = "Apply now",
    override val finishDate: String = "Finish",
    override val setUpFingerprintId: String = "",
    // Home
    override val addYourPaypalAccount: String = "Add your PayPal account",
    override val addPaypalDescription: String = "You can now move money from PayPal right into your bank account",
    override val addPaypalTitleHint: String = "There's a new kid on the block",
    override val addAccount: String = "Add account",
    override val addAccountDescription: String = "A bank account, card, mobile wallet or PayPal account",
    override val myAccounts: String = "My accounts",
    override val myPaypalAccountHeader: String = "My Paypal accounts",
    override val myBalance: String = "My balance",
    override val youHaveHint: String = "You have",

    // MoreScreen Hint
    override val notificationsTitle: String = "Notifications",
    override val notificationsSubtitle: String = "View and manage your notifications",
    override val securityTitle: String = "Security",
    override val securitySubtitle: String = "Change your sign-in details and password",
    override val supportTitle: String = "Support",
    override val supportSubtitle: String = "Email, call or find us on social media",
    override val changeLanguageTitle: String = "Change Language",
    override val recommendEquityToFriendTitle: String = "Recommend Equity mobile to a friend",
    override val signOut: String = "Sign out",

    // Savings
    override val save: String = "Save",
    override val openAnAccount: String = "Open an account",
    override val learnMore: String = "Learn more",
    override val savingsTitle: String = "Grow your Money",
    override val savingsDescription: String = "Equity Bank offers a variety of products that helps you save and invest your money to ensure you grow your wealth",
    override val classicSavingsTitle: String = "Classic savings",
    override val classicSavingsSubtitle: String = "Save any amount as frequently as you can while earning a simple interest",
    override val goalSavingsTitle: String = "Goal savings",
    override val goalSavingsSubtitle: String = "Set your goals and start saving towards them immediately while earning interest",
    override val fixedSavingsTitle: String = "Fixed deposit",
    override val fixedSavingsSubtitle: String = "Access your deposit amount plus interest at the end of a fixed saving period",
    override val callSavingsTitle: String = "Call deposit",
    override val callSavingsSubtitle: String = "Start saving and have immediate access to your funds plus interest, without any penalty",

    // Security Screen Hint
    override val changeYourPasswordTitle: String = "Change your password",
    override val changeYourPasswordSubtitle: String = "Create a new password",
    override val manageYourPinTitle: String = "Manage your PIN",
    override val manageYourPinSubtitle: String = "Reset or change your PIN",
    override val manageSecurityQuestionTitle: String = "Manage security questions",
    override val manageSecurityQuestionSubtitle: String = "Update your security questions",
    override val enableTouchTitle: String = "Enable Touch ID",
    override val enableTouchSubtitle: String = "Unlock with Touch ID",
    override val manageYourDevicesTitle: String = "Manage your devices",
    override val manageYourDevicesSubtitle: String = "Manage the devices connected to your profile"
) : IStringResources
