package com.dev.chacha.resources.strings.sw

import com.dev.chacha.resources.strings.IStringResources

data class Swahili(
    override val appName: String = "EquityMobile",
    override val passwordVisibleContentDescription: String = "Ficha nenosiri",
    override val passwordHiddenContentDescription: String = "Onyesha nenosiri",
    override val dontHaveAnAccountYet: String = "Huna akaunti bado? Tafadhali",
    override val signUp: String = "Jisajili!",
    override val email: String = "Barua pepe",
    override val register: String = "Jiandikishe",
    override val createYourProfile: String = "Unda wasifu wako",
    override val country: String = "Nchi",
    override val selectCountry: String = "Chagua nchi",
    override val accountNumberHint: String = "Ingiza nambari ya akaunti au simu",
    override val accountNumberTitle: String = "Nambari ya akaunti",
    override val idNumberHint: String = "Ingiza nambari yako ya kitambulisho",
    override val idNumberTitle: String = "Nambari ya kitambulisho",
    override val agreeToTermsAndPrivacyPolicy: String = "Nakubali masharti na sera ya faragha",
    override val createProfileAddAccounts: String = "Unda wasifu + ongeza akaunti",
    override val welcomeBack: String = "Karibu tena",
    override val helloThere: String = "Habari",
    override val emailHint: String = "Anwani ya barua pepe au nambari ya simu",
    override val loginPasswordHint: String = "Ingiza nenosiri",
    override val loginPasswordTitle: String = "Nenosiri",
    override val forgotPassword: String = "Umesahau Nenosiri?",
    override val enterPasswordToSignIn: String = "Ingiza nenosiri",
    override val loginHeaderDescription: String = "Ingia kuendelea. Kumbuka, nenosiri lako ni la siri, usishiriki na mtu yeyote.",
    override val alreadyHaveAnAccount: String = "Tayari una akaunti? Nenda kwenye",
    override val signIn: String = "Ingia",
    override val username: String = "Jina la mtumiaji",
    override val loginHint: String = "Jina la mtumiaji / Barua pepe",
    override val login: String = "Ingia",
    override val createPinHeader: String = "Unda nambari yako ya siri ya tarakimu 4",
    override val createPinHint: String = "Hakikisha kuwa PIN yako ni ya kipekee na salama",
    override val passwordHint: String = "Ingiza nenosiri",
    override val reEnterPasswordHint: String = "Ingiza tena nenosiri lako",
    override val createPassword: String = "Unda nenosiri",
    override val createPasswdHeader: String = "Unda nenosiri imara",
    override val createPasswordHint: String = "Kadiri ngumu ya nenosiri, ndivyo bora na salama zaidi",
    override val confirmPassword: String = "Thibitisha Nenosiri",
    override val passwordTitle: String = "Nenosiri",
    override val validateHeader: String = "Nini kinahitajika?",
    override val validateLetter: String = "Inapaswa kuwa na nambari, herufi kubwa na ndogo",
    override val validateCharLong: String = "Lazima iwe na herufi angalau 8",
    override val validateSpecialChar: String = "Inapaswa kuwa na herufi maalum (k.m !@#$&)",
    override val passwordMatch: String = "Nenosiri lazima lifanane",
    override val pinValidateHeader: String = "Jinsi ya kuunda PIN salama:",
    override val validateSequence: String = "Epuka mfuatano wa nambari (k.m. 1234 au 9876)",
    override val validateRepetitive: String = "Epuka kutumia nambari zinazorudiwa (k.m. 0000, 1111)",
    override val verifyHeader: String = "Ungependa kuthibitishwa vipi?",
    override val selectHint: String = "Chagua moja ya chaguo hapa chini",
    override val greetings: String = "Usiku mwema, Stephen",
    override val homeHint: String = "Ungependa kufanya nini leo?",
    override val purpose1: String = "Mkopo huu unapatikana kwa wanachama wa Equity ambao wamekuwa na akaunti yao ya benki ya Equity kwa angalau miezi sita",
    override val purpose2: String = "Unaweza kukopa hadi 1,000,000 KES, huku ukipata kulipa kwa kipindi cha miezi 12.",
    override val purpose3: String = "Ninaweza kukopa kiasi gani?",
    override val purpose4: String = "Unaweza kuangalia kikomo cha mkopo wako na kugundua",
    override val loanDesc: String = "Equity inatoa aina mbalimbali za mikopo kukusaidia kufikia malengo yako. Angalia bidhaa zetu za mikopo ili kupata ile inayokufaa",
    override val purpose: String = "Kopa hadi 1,000,000 KES na lipa kwa hadi miezi kumi na mbili",
    override val manageDevices: String = "Unaweza kuondoa kifaa chochote kilichounganishwa na wasifu wako",
    override val getInTouch: String = "Tufikie wakati wowote unapohitaji msaada na timu yetu yenye vipaji itafurahi kukusaidia",
    override val favourite: String = "Mwasiliani wako pendwa atatokea hapa. Ongeza mpya haraka kufanya shughuli",
    override val ownEquityAccount: String = "Akaunti ya Equity yako",
    override val anotherEquityAccount: String = "Akaunti nyingine ya Equity",
    override val payTopUp: String = "Lipa kwa kadi",
    override val creditPrepaid: String = "Kadi za Mkopo na Prepaid",
    override val mobileWallet: String = "Pochi ya simu",
    override val sendToMobile: String = "Tuma kwa watoa huduma wa simu",
    override val anotherBank: String = "Benki nyingine",
    override val payBill: String = "Lipa bili",
    override val buyAirtime: String = "Nunua muda wa maongezi",
    override val buyGoods: String = "Nunua bidhaa",
    override val agent: String = "Mwakilishi",
    override val setUpFingerprintId: String = "Sanidi Kitambulisho cha Kidole",
    override val haveYouForgottenYourPassword: String = "Je, umesahau nenosiri lako",
    override val forgotPasswordDescription: String = "Tutakutumia barua pepe au ujumbe wa maandishi na kiunga cha kukusaidia kuweka upya nenosiri lako",
    override val emailOrMobileNumber: String = "Anwani ya barua pepe au nambari ya simu",
    override val pinTitle: String = "PIN",
    override val pinHint: String = "Ingiza Pin",
    override val confirmPin: String = "Thibitisha PIN",
    override val confirmPinHint: String = "Thibitisha PIN",
    override val setPin: String = "Weka PIN",
    override val createDialogDescription: String = "Sasa unaweza kusahilisha baadhi ya shughuli zako za kawaida na PIN ya kipekee na rahisi kukumbuka ya tarakimu 4",
    override val yowOweHint: String = "",
    override val apply: String = "Tuma Maombi",
    override val selectFinishDateTitle: String = "Chagua Tarehe ya Mwisho",
    override val today: String = "Leo",
    override val notFoundEmail: String = "haikupatikana\n",
    override val copyToClipboard: String = "Imehamishwa kwenye ubao wa kunakili",
    override val openAccount: String = "Fungua akaunti",
    override val loans: String = "Mikopo",
    override val borrow: String = "Kopa",
    override val payLoan: String = "Lipa mkopo",
    override val getLoan: String = "Pata mkopo",
    override val oneMonthLoanTitle: String = "Mkopo wa Mwezi Mmoja",
    override val oneMonthLoanSubtitle: String = "Kopa hadi 1,000,000 KES na ulipe katika mwezi mmoja",
    override val installmentLoanTitle: String = "Mkopo wa Malipo ya Awamu",
    override val installmentLoanSubtitle: String = "Kopa hadi 1,000,000 KES na ulipe kwa hadi miezi kumi na mbili",
    override val pensionLoanTitle: String = "Mkopo wa Pensheni",
    override val pensionLoanSubtitle: String = "Mkopo kwa wanachama wanaopokea pensheni ya kila mwezi",
    override val salaryAdvanceLoanTitle: String = "Mkopo wa Malipo ya Mshahara Mbele",
    override val salaryAdvanceLoanSubtitle: String = "Mkopo wa muda mfupi kwa wanachama wanaopokea mshahara wa kila mwezi",
    override val ecosystemLoanTitle: String = "Mkopo wa Ekolojia",
    override val ecosystemLoanSubtitle: String = "Bidhaa hii ni kwa wafanyabiashara waliothibitishwa ambao huuza bidhaa zilizoko na muuzaji wa ndani au msaidizi wa ndani",

// Kuhusu Mkopo wa Mwezi Mmoja
    override val aboutOneMonthLoan1: String = "Mkopo huu unapatikana kwa wanachama wa Equity ambao wamekuwa na akaunti yao ya benki ya Equity kwa angalau miezi sita",
    override val aboutOneMonthLoan2: String = "Unaweza kukopa hadi 1,000,000 KES, ambayo inaweza kulipwa katika mwezi mmoja",
    override val aboutOneMonthLoan3: String = "Ninaweza kukopa kiasi gani?",
    override val aboutOneMonthLoan4: String = "Unaweza kuangalia kikomo cha mkopo wako ili kugundua",

// Kuhusu Mkopo wa Malipo ya Awamu
    override val aboutInstallmentLoan1: String = "Mkopo huu unapatikana kwa wanachama wa Equity ambao wamekuwa na akaunti yao ya benki ya Equity kwa angalau miezi sita",
    override val aboutInstallmentLoan2: String = "Unaweza kukopa hadi 1,000,000 KES, ambayo inaweza kulipwa kwa kipindi cha miezi 12",
    override val aboutInstallmentLoan3: String = "Ninaweza kukopa kiasi gani?",
    override val aboutInstallmentLoan4: String = "Unaweza kuangalia kikomo cha mkopo wako ili kugundua",

// Kuhusu Mkopo wa Pensheni
    override val aboutPensionLoan1: String = "Kama mpokeaji wa pensheni, ni muhimu kwako kufurahia wakati wako wa kustaafu na wakati huo huo kuwa na uwezo wa kupata kila unachohitaji na unachotaka. Mkopo wa Pensheni umebuniwa kukusaidia kukidhi mahitaji yako ya dharura, na unategemea wasifu wako wa akaunti",
    override val aboutPensionLoan2: String = "Kwa mkopo huu, tunatoa kipindi cha kurudisha hadi miezi 48. Unaweza kustahiki mkopo wa hadi 3,800,000 KES",
    override val aboutPensionLoan3: String = "Ninaweza kukopa kiasi gani?",
    override val aboutPensionLoan4: String = "Unaweza kuangalia kikomo cha mkopo wako ili kugundua",
// Kuhusu Mkopo wa Mshahara Mbele
    override val aboutSalaryLoan1: String = "Huu ni mkopo wa muda mfupi kukusaidia kukidhi mahitaji yako ya dharura. Mkopo huu unategemea wasifu wako.",
    override val aboutSalaryLoan2: String = "Kwa mkopo huu, tunatoa kipindi cha kurudisha hadi miezi 12.\n Ili kustahiki, mshahara wako lazima uwe umekuwa ukiingia kwenye akaunti yako ya Equity Bank kwa angalau miezi mitatu",
    override val aboutSalaryLoan3: String = "Unaweza kustahiki kiwango kikubwa cha hadi mara 4 ya mshahara wako wa kila mwezi.",
    override val aboutSalaryLoan4: String = "Kiasi chochote kilichozidi 300,000 KES lazima kiwekwe dhamana kwa hati ya magari au hati ya umiliki.",
    override val aboutSalaryLoan5: String = "Ninaweza kukopa kiasi gani?",
    override val aboutSalaryLoan6: String = "Unaweza kuangalia kikomo cha mkopo wako ili kugundua",

// Kuhusu Mkopo wa Ekolojia
    override val aboutEcosystemLoan1: String = "Bidhaa hii ni kwa wafanyabiashara waliothibitishwa ambao huuza bidhaa zilizoko na muuzaji wa ndani au msaidizi wa ndani. Kupitia kituo hiki, wafanyabiashara wanaweza kutoa fedha kwa mahitaji ya ufadhili wa hisa, haraka na kwa urahisi, wakati wowote inapohitajika.",
    override val aboutEcosystemLoan2: String = "Muuzaji ana chaguo la kuweka bima bidhaa wanazonunua, ili kufidia hasara au uharibifu wowote unaweza kutokea wakati bidhaa ziko njiani",
    override val aboutEcosystemLoan3: String = "Ninaweza kukopa kiasi gani?\n- Kiwango cha chini cha KES\n- Kiwango cha juu cha 1,000,000 KES (Hii inategemea msingi\n- Kiasi chochote kilichozidi 1,000,000 KES kinapaswa kuwa na dhamana kamili",
    override val aboutEcosystemLoan4: String = "Kiasi chochote kilichozidi 300,000 KES lazima kiwekwe dhamana kwa hati ya magari au hati ya umiliki.",
    override val aboutEcosystemLoan5: String = "Mkopo wa mfumo wa ikolojia ni kituo cha ufadhili wa hisa kinachozunguka. Kila kiasi kinachotolewa kitarejeshwa ndani ya kipindi kilichokubaliwa, ambacho ni kisichozidi siku 30, kulingana na segement ya mteja. Kikomo cha jumla cha mkopo kimeidhinishwa kwa kipindi cha miezi 3, ambacho kinaweza kufanyiwa mapitio kulingana na tathmini ya utendaji uliopita",
    override val aboutEcosystemLoan6: String = "Ninaweza kukopa kiasi gani?",
    override val aboutEcosystemLoan7: String = "Unaweza kuangalia kikomo cha mkopo wako ili kugundua",

// Kuhusu Akaunti ya Klasiki
    override val aboutClassicSavingsTitle: String = "Akaunti ya Klasiki",
    override val aboutClassicAccount: String = "Hifadhi kiasi chochote na weka amana mara kwa mara, ukipata faida ya riba iliyohesabiwa kila mara kwenye amana.",
    override val aboutClassicInterestTitle: String = "Kiwango cha riba",
    override val aboutClassicInterestRateDesc1: String = "Riba utakayopata na akaunti ya Hifadhi Klasiki imehesabiwa kulingana na riba rahisi. Inategemea kiasi unachoweka kwenye akaunti na inaweza kubadilika.",
    override val aboutClassicAccountRateDesc2: String = "Riba italipwa tu kwa salio la akaunti la zaidi ya 20,000.00 KES na itakamilishwa mwishoni mwa mwaka na/au wakati wa kufunga akaunti.",
    override val aboutClassicInterestInformation: String = "Kwa maelezo zaidi kuhusu kiwango cha riba,\nBonyeza hapa.",
    override val whatShouldYouGetAccount: String = "Kwa nini unapaswa kupata akaunti hii?",
    override val whatShouldYouGetClassicAccountDesc: String = "• Weka fedha kwenye akaunti mara nyingi unavyotaka.\n• Akiba yako inapatikana kwa urahisi kwa ombi.\n• Pata mapato ya kila mwaka.\n• Hakuna malipo ya kuhama pesa kutoka akaunti yako ya akiba kwenda akaunti ya benki.",
    override val aboutClassicBonus: String = "Bonasi:\n• Hakuna malipo au ada za kila mwezi kwa kufanya kazi na akaunti hii.",
    override val whatYouNeedClassicAccount: String = "Unahitaji nini",
    override val whatYouNeedClassicAccountDesc: String = "Unahitaji salio la ufunguzi wa chini la 1,000 KES na wasifu wa Equity online ulio hai.",
    override val aboutClassicWithdrawals: String = "Uondoaji:",
    override val aboutClassicWithdrawDesc1: String = "Uondoaji mmoja wa bure unaruhusiwa kwa mwezi. Malipo ya uondoaji ya 60.00 KES yanatozwa kwa uondoaji wowote unaofuata ndani ya mwezi huo huo.",
    override val aboutClassicAccountWithdraw3: String = "Ikiwa uondoaji wako unaiacha akaunti na chini ya 20,000 KES, utapoteza riba iliyopatikana.",
    override val aboutClassicAccountWithdraw4: String = "Kwa kufunga akaunti, pesa zitaondolewa na kuhamishiwa kwenye akaunti yako ya asili.",
    // Kuhusu Akaunti ya Hifadhi ya Wito
    override val aboutCallDepositTitle: String = "Akaunti ya Hifadhi ya Wito",
    override val aboutCallDepositDesc: String = "Akaunti hii ya akiba inakuruhusu kuweka kiasi cha msingi, kupata riba, na kupata pesa zako wakati wowote.",
    override val aboutCallDepositInterest: String = "Kiwango cha riba",
    override val aboutCallDepositInformation: String = "Kwa maelezo zaidi kuhusu kiwango cha riba, bonyeza hapa.",
    override val aboutCallBenefit: String = "• Wakati wa kipindi cha uwekezaji, riba hupatikana kila siku.\n• Hakuna kiwango cha juu cha kuweka amana.\n• Upatikanaji wa akaunti usio na kikomo kwenye simu na mtandaoni.\n• Ripoti za e-mwezi bure.\n• Hakuna malipo ya kila mwezi kwa akaunti yako.",
    override val idealAccountCall: String = "Akaunti hii ni bora ikiwa:",
    override val callDepositIdealDesc: String = "• Una kipato kinachoweza kutumika.\n• Unatafuta njia nzuri ya kupata faida kwenye akiba yako.",
    override val whatYouNeedCallDepositTitle: String = "Unahitaji nini",
    override val whatYouNeedCallDeposit: String = "Unahitaji kuwa na umri wa miaka 18 na wasifu wa Equity ulio hai na salio la chini la 50,000 KES. Kipindi cha juu cha kuweka amana ni miezi 12.",
    override val callDepositTopAndWithdrawTitle: String = "Kuweka na Kutoa",
    override val callDepositTopAndWithdraw: String = "Weka pesa kwenye akaunti yako mara nyingi unavyotaka kupitia chaguzi za Move money zilizopo. Uondoaji wa sehemu unaruhusiwa. Hata hivyo, ikiwa akaunti yako itafungwa, fedha zitahamishiwa kwenye akaunti yako ya asili.",
    override val callDepositAccountClosure: String = "Kufunga Akaunti:",
    override val callDepositAccountClosureDesc: String = "Unaweza kufunga akaunti yako kwa mikono baada ya siku moja kamili ya akaunti kufunguliwa. Fedha basi zitahamishiwa kwenye akaunti yako ya asili.",

// Kuhusu Akaunti ya Hifadhi Imara
    override val aboutFixedAccount: String = "Akaunti ya Hifadhi Imara",
    override val aboutFixedAccountDesc: String = "Akaunti hii ni bora ikiwa unatafuta njia ya kupata kiasi cha riba kinachofaa kwenye pesa ya ziada unayo.",
    override val aboutFixedDepositInterest: String = "Kiwango cha riba",
    override val aboutFixedDepositDesc: String = "Akaunti hupata riba rahisi kila siku.",
    override val aboutFixedDepositInformation: String = "Kwa maelezo zaidi kuhusu kiwango cha riba,\nBonyeza hapa.",
    override val aboutFixedShouldYouAccount: String = "Kwa nini unapaswa kupata akaunti hii?",
    override val aboutFixedShouldYouThisAccountDesc: String = "• Kipindi cha chini cha Akaunti ya Hifadhi Imara ni mwezi mmoja tu.\n• Kiwango cha amana na riba ni cha kudumu wakati wa kipindi cha uwekezaji.\n• Wakati wa kufungua akaunti hii, unafahamishwa kuhusu riba utakayopata.\n• Malipo ya msingi na riba hufanywa wakati wa ukomavu au kufunga akaunti.\n• KES inaungwa mkono.\n• Hakuna malipo ya kila mwezi.\n• Unaweza kuchagua kurekebisha akiba yako katika akaunti mpya ya Hifadhi Imara mwishoni mwa kipindi chako cha amana.",
    override val aboutWhatDoNeedToOpenHint: String = "Unahitaji nini kupata akaunti hii?",
    override val aboutWhatDoNeedToOpenDesc: String = "Unahitaji salio la ufunguzi wa chini la 50,000 KES na wasifu wa Equity ulio hai mtandaoni.",
    override val fixedWithdrawal: String = "Ikiwa utatoa fedha zako kabla ya kufikia kipindi cha amana ulichochagua, akaunti itafungwa na riba iliyopatikana itapunguzwa. Fedha basi zitahamishiwa kwenye akaunti yako ya asili.",
// Kuhusu Akaunti ya Malengo
    override val aboutGoalSavingsTitle: String = "Akaunti ya Malengo",
    override val aboutGoalAccount: String = "Akaunti hii ya akiba inakuruhusu kuweka lengo, kuweka pesa, na kuweka akiba kwa urahisi kuelekea malengo yako ya kifedha.",
    override val goalInterestTitle: String = "Kiwango cha Riba",
    override val aboutGoalInterestRate: String = "Kwa maelezo zaidi kuhusu kiwango cha riba,\nBonyeza hapa.",
    override val aboutGoalAccountBenefit: String = "Manufaa:",
    override val aboutGoalAccountIdeal: String = "Akaunti hii ni bora ikiwa:",
    override val aboutGoalAccountIdealDesc: String = "\n&#8226; Una kipato cha kawaida na thabiti.\n&#8226; Una kipato kinachoweza kutumika.\n&#8226; Unatafuta njia nzuri ya kuweka akiba kuelekea malengo yako ya kifedha.",
    override val aboutGoalAccountWhatYouNeed: String = "Unahitaji nini",
    override val aboutGoalAccountWhatYouNeedDescription: String = "Unahitaji kuwa na umri wa miaka 18 na wasifu wa Equity ulio hai na salio la ufunguzi wa chini la 300.00 KES. Akaunti hii haina urefu wa kima cha chini wa muda.",
    override val aboutGoalAccountTopUpAndWithdraw: String = "Kuweka na Kutoa",
    override val aboutGoalAccountTopUpAndWithdrawDesc: String = "Weka pesa kwenye akaunti yako mara nyingi unavyopenda na Move money. Unaweza kufanya uondoaji wa bure mara moja kila miezi 6. Baada ya hapo, malipo ya uondoaji wa 60.00 KES yanatozwa.",
    override val aboutGoalAccountAccountClosure: String = "Kufunga Akaunti",
    override val aboutGoalAccountAccountClosureDesc: String = "Unaweza kufunga akaunti yako kwa mikono wakati wowote. Fedha basi zitahamishiwa kwenye akaunti yako ya asili.",

// Wasiliana Nasi
    override val contactUs: String = "Wasiliana nasi",
    override val equityContact: String = "+254 763 063000",
    override val emailUs: String = "Tutumie Barua pepe",
    override val equityEmail: String = "info@equitybank.co.ke",
    override val website: String = "Tembelea tovuti yetu",
    override val equityWebsite: String = "https://equitygroupholdings.com/ke/",
    override val twitter: String = "Tufuate kwenye Twitter",
    override val equityTwitter: String = "@KeEquityBank",
    override val facebook: String = "Tuambie kwenye Facebook",
    override val equityFacebook: String = "https://www.facebook.com/KeEquityBank/",
    override val linkedin: String = "Tufuate kwenye LinkedIn",
    override val equityLinkedin: String = "Equity Bank Limited",

// Simamia Vifaa
    override val mobileDevice: String = "Vifaa vya Mkononi",
    override val noOfMobileDevices: String = "% kifaa",
    override val webDevices: String = "Vifaa vya Wavuti",
    override val webDevicesNo: String = "% vifaa",
    override val getInTouchDesc: String = "Wasiliana nasi wakati wowote unapohitaji msaada na timu yetu yenye vipaji itakusaidia kwa furaha",
    override val whichDeviceWouldYouLikeToRemove: String = "Unataka kufuta kifaa kipi?",
    override val mobileDevicesDesc: String = "Chagua kifaa unachotaka kufuta. Kuunganisha tena, tu ingia kwenye wasifu wako kwa kutumia kifaa hicho",
    override val changeYourPin: String = "Badilisha PIN yako",
    override val changeYourExistingPin: String = "Badilisha PIN yako ya sasa",
    override val resetYourPin: String = "Rudisha PIN yako",
    override val resetYourPinIfYouVeForgottenIt: String = "Rudisha PIN yako ikiwa umesahau",
    override val makeSureYourPinEasy: String = "Hakikisha PIN yako ni rahisi kukumbuka",
    override val enterCurrentPin: String = "Weka PIN yako ya sasa",
    override val enterNewPin: String = "Weka PIN mpya",
    override val newPin: String = "PIN Mpya",
    override val currentPin: String = "PIN ya Sasa",
    override val confirmNewPassword: String = "Thibitisha nenosiri jipya",
    override val newPassword: String = "Nenosiri Jipya",
    override val currentPassword: String = "Nenosiri la Sasa",

// Arifa
    override val selectTheAccountYouWantToGetTransactionAlertFor: String = "Chagua akaunti unayotaka kupokea arifa za shughuli kwa",
    override val howDoYouWantToReceiveYourAlerts: String = "Unataka kupokea arifa zako vipi?",
    override val notificationDisabled: String = "Arifa imelemazwa",
    override val smsAlert: String = "Arifa za SMS",
    override val alertEnabled: String = "Arifa imewezeshwa",
    override val enableAllAccounts: String = "Washa akaunti zote",
    override val notificationEnabled: String = "Arifa zimewezeshwa",
    override val selectTheAccountYouWantToGetRemindersAlertFor: String = "Chagua akaunti unayotaka kupokea kumbusho kwa",
    override val howDoYouWantToReceiveYourNotification: String = "Unataka kupokea arifa zako vipi?",
    override val emailNotification: String = "Barua pepe",
    override val pushNotification: String = "Arifa ya kubonyeza",
    override val accountUser: String = "Stephen Chacha Marwa",
    override val accountNumber: String = "123456789",
    override val buyForSomeoneNew: String = "Nunua kwa mtu mpya",
    override val searchForCountry: String = "Tafuta nchi",
    override val getInTouchSubtitle: String = "Barua pepe, piga simu au tukutane kwenye mitandao ya kijamii",
    override val makePayment: String = "Fanya Malipo",
    override val sendToSomeoneNew: String = "Tuma kwa mtu mpya",
    override val enterAnAccountNumber: String = "Weka namba ya akaunti",
    override val withdrawFromPaypal: String = "Ondoa kutoka PayPal",
    override val withdrawCash: String = "Ondoa fedha taslimu",
// Kutuma pesa
    override val sendMoney: String = "Tuma pesa",
    override val westernUnionSendMoneySubtitle: String = "Tuma pesa kimataifa kupitia Western Union",
    override val receiveMoney: String = "Pokea Pesa",
    override val westernUnionReceiveMoneySubtitle: String = "Pokea pesa kwa kuingiza namba ya ufuatiliaji wa Western Union",
    override val signInWithTouchId: String = "Ingia kwa kutumia Touch ID",
    override val recommend: String = "Tumia",
    override val activateChatBanking: String = "Washa Benki ya Mazungumzo",
    override val activateChatBankingDesc: String = "Fanya shughuli na Msaidizi wa Kielektroniki wa Equity",
    override val addAnEquityAccount: String = "Ongeza akaunti ya Equity",
    override val addAnEquityAccountDes: String = "Ongeza akaunti ya Equity kwenye wasifu wako",
    override val addYourPaypalAccountDesc: String = "unganisha akaunti mbili za PayPal kwenye akaunti yako ya benki",
    override val darkMode: String = "Hali ya Giza",
    override val applyNow: String = "Tuma Maombi Sasa",
    override val finishDate: String = "Mwisho",
// Nyumbani
    override val addYourPaypalAccount: String = "Ongeza akaunti yako ya PayPal",
    override val addPaypalDescription: String = "Sasa unaweza kuhamisha pesa kutoka PayPal moja kwa moja kwenye akaunti yako ya benki",
    override val addPaypalTitleHint: String = "Kuna mtoto mpya kwenye mtaa",
    override val addAccount: String = "Ongeza akaunti",
    override val addAccountDescription: String = "Akaunti ya benki, kadi, mkoba wa simu au akaunti ya PayPal",
    override val myAccounts: String = "Akaunti zangu",
    override val myPaypalAccountHeader: String = "Akaunti zangu za Paypal",
    override val myBalance: String = "Salio langu",
    override val youHaveHint: String = "Unayo",

// ZaidiScreen Hint
    override val notificationsTitle: String = "Arifa",
    override val notificationsSubtitle: String = "Angalia na simamia arifa zako",
    override val securityTitle: String = "Usalama",
    override val securitySubtitle: String = "Badilisha maelezo yako ya kuingia na nenosiri",
    override val supportTitle: String = "Msaada",
    override val supportSubtitle: String = "Barua pepe, piga simu au tukutane kwenye mitandao ya kijamii",
    override val changeLanguageTitle: String = "Badilisha Lugha",
    override val recommendEquityToFriendTitle: String = "Pendekeza Equity simu kwa rafiki",
    override val signOut: String = "Toka",
// Akiba
    override val save: String = "Hifadhi",
    override val openAnAccount: String = "Fungua akaunti",
    override val learnMore: String = "Jifunze zaidi",
    override val savingsTitle: String = "Jenga Utajiri wako",
    override val savingsDescription: String = "Benki ya Equity inatoa aina mbalimbali za bidhaa ambazo zinakusaidia kuweka akiba na kuwekeza pesa yako ili kuhakikisha unapanua utajiri wako",
    override val classicSavingsTitle: String = "Akiba ya kawaida",
    override val classicSavingsSubtitle: String = "Hifadhi kiasi chochote mara kwa mara huku ukipata riba rahisi",
    override val goalSavingsTitle: String = "Akiba ya Malengo",
    override val goalSavingsSubtitle: String = "Wekea malengo yako na anza kuweka akiba mara moja wakati huo ukilipwa riba",
    override val fixedSavingsTitle: String = "Hifadhi ya Kudumu",
    override val fixedSavingsSubtitle: String = "Fikia kiasi chako cha amana pamoja na riba mwishoni mwa kipindi cha kuweka akiba",
    override val callSavingsTitle: String = "Akiba ya Mwito",
    override val callSavingsSubtitle: String = "Anza kuweka akiba na upate ufikiaji wa haraka kwa pesa zako pamoja na riba, bila adhabu yoyote",

// Usalama wa Skrini
    override val changeYourPasswordTitle: String = "Badilisha nenosiri lako",
    override val changeYourPasswordSubtitle: String = "Tengeneza nenosiri jipya",
    override val manageYourPinTitle: String = "Sakinisha namba yako ya siri",
    override val manageYourPinSubtitle: String = "Rekebisha au badilisha namba yako ya siri",
    override val manageSecurityQuestionTitle: String = "Sakinisha maswali yako ya usalama",
    override val manageSecurityQuestionSubtitle: String = "Sasisha maswali yako ya usalama",
    override val enableTouchTitle: String = "Wezesha Touch ID",
    override val enableTouchSubtitle: String = "Fungua kwa Touch ID",
    override val manageYourDevicesTitle: String = "Sakinisha vifaa vyako",
    override val manageYourDevicesSubtitle: String = "Simamia vifaa vilivyounganishwa na wasifu wako",
    override val titleActivityMain: String = "MainActivity",
    override val firstFragmentLabel: String = "Kipande cha Kwanza",
    override val secondFragmentLabel: String = "Kipande cha Pili",
    override val next: String = "Ifuatayo",
    override val previous: String = "Iliyopita",
    override val changePasswordTitle: String = "Badilisha nenosiri lako",
    override val changePasswordDescription: String = "Unda nenosiri jipya",
    override val confirmPass: String = "Thibitisha",
    override val schedulePayment: String = "Panga malipo",
    override val westernUnionHint: String = "Western Union",
    override val paypalHint: String = "PayPal",
    override val addFavorite: String = "Ongeza pendwa",
    override val favorite: String = "Pendwa",




    ): IStringResources
