package com.dev.chacha.resources.strings

interface IStringResources {
    val appName: String
    val passwordVisibleContentDescription: String
    val passwordHiddenContentDescription: String
    val dontHaveAnAccountYet: String
    val signUp: String
    val email: String
    val register: String
    val createYourProfile: String
    val country: String
    val selectCountry: String
    val accountNumberHint: String
    val accountNumberTitle: String
    val idNumberHint: String
    val idNumberTitle: String
    val agreeToTermsAndPrivacyPolicy: String
    val createProfileAddAccounts: String
    val welcomeBack: String
    val helloThere: String
    val emailHint: String
    val loginPasswordHint: String
    val loginPasswordTitle: String
    val forgotPassword: String
    val enterPasswordToSignIn: String
    val loginHeaderDescription: String
    val alreadyHaveAnAccount: String
    val signIn: String
    val username: String
    val loginHint: String
    val login: String
    val createPinHeader: String
    val createPinHint: String
    val passwordHint: String
    val reEnterPasswordHint: String
    val createPassword: String
    val createPasswdHeader: String
    val createPasswordHint: String
    val confirmPassword: String
    val passwordTitle: String
    val validateHeader: String
    val validateLetter: String
    val validateCharLong: String
    val validateSpecialChar: String
    val passwordMatch: String
    val pinValidateHeader: String
    val validateSequence: String
    val validateRepetitive: String
    val verifyHeader: String
    val selectHint: String
    val greetings: String
    val homeHint: String
    val purpose1: String
    val purpose2: String
    val purpose3: String
    val purpose4: String
    val loanDesc: String
    val purpose: String
    val manageDevices: String
    val getInTouch: String
    val favourite: String
    val titleActivityMain: String
    val firstFragmentLabel: String
    val secondFragmentLabel: String
    val next: String
    val previous: String
    val changePasswordTitle: String
    val changePasswordDescription: String
    val confirmPass: String
    val schedulePayment: String
    val westernUnionHint: String
    val paypalHint: String
    val addFavorite: String
    val favorite: String
    val ownEquityAccount: String
    val anotherEquityAccount: String
    val payTopUp: String
    val creditPrepaid: String
    val mobileWallet: String
    val sendToMobile: String
    val anotherBank: String
    val payBill: String
    val buyAirtime: String
    val buyGoods: String
    val agent: String
    val addYourPaypalAccount: String
    val addPaypalDescription: String
    val addPaypalTitleHint: String
    val addAccount: String
    val addAccountDescription: String
    val myAccounts: String
    val myPaypalAccountHeader: String
    val myBalance: String
    val youHaveHint: String
    val yowOweHint: String
    val notificationsTitle: String
    val notificationsSubtitle: String
    val securityTitle: String
    val securitySubtitle: String
    val supportTitle: String
    val supportSubtitle: String
    val changeLanguageTitle: String
    val recommendEquityToFriendTitle: String
    val signOut: String
    val save: String
    val openAnAccount: String
    val learnMore: String
    val savingsTitle: String
    val savingsDescription: String
    val classicSavingsTitle: String
    val classicSavingsSubtitle: String
    val goalSavingsTitle: String
    val goalSavingsSubtitle: String
    val fixedSavingsTitle: String
    val fixedSavingsSubtitle: String
    val callSavingsTitle: String
    val callSavingsSubtitle: String
    val changeYourPasswordTitle: String
    val changeYourPasswordSubtitle: String
    val manageYourPinTitle: String
    val manageYourPinSubtitle: String
    val manageSecurityQuestionTitle: String
    val manageSecurityQuestionSubtitle: String
    val enableTouchTitle: String
    val enableTouchSubtitle: String
    val manageYourDevicesTitle: String
    val manageYourDevicesSubtitle: String
    val haveYouForgottenYourPassword: String
    val forgotPasswordDescription: String
    val emailOrMobileNumber: String
    val pinTitle: String
    val pinHint: String
    val confirmPin: String
    val confirmPinHint: String
    val setPin: String
    val createDialogDescription: String
    val setUpFingerprintId: String
    val applyNow: String
    val apply:String
    val selectFinishDateTitle: String
    val today: String
    val finishDate: String
    val notFoundEmail: String
    val copyToClipboard: String
    val openAccount: String
    val loans: String
    val borrow: String
    val payLoan: String
    val getLoan: String
    val oneMonthLoanTitle: String
    val oneMonthLoanSubtitle: String
    val installmentLoanTitle: String
    val installmentLoanSubtitle: String
    val pensionLoanTitle: String
    val pensionLoanSubtitle: String
    val salaryAdvanceLoanTitle: String
    val salaryAdvanceLoanSubtitle: String
    val ecosystemLoanTitle: String
    val ecosystemLoanSubtitle: String

    // About One Month loan
    val aboutOneMonthLoan1: String
    val aboutOneMonthLoan2: String
    val aboutOneMonthLoan3: String
    val aboutOneMonthLoan4: String

    // About Installment loan
    val aboutInstallmentLoan1: String
    val aboutInstallmentLoan2: String
    val aboutInstallmentLoan3: String
    val aboutInstallmentLoan4: String

    // About Pension loan
    val aboutPensionLoan1: String
    val aboutPensionLoan2: String
    val aboutPensionLoan3: String
    val aboutPensionLoan4: String

    // About Salary Advance loan
    val aboutSalaryLoan1: String
    val aboutSalaryLoan2: String
    val aboutSalaryLoan3: String
    val aboutSalaryLoan4: String
    val aboutSalaryLoan5: String
    val aboutSalaryLoan6: String

    // About EcoSystem loan
    val aboutEcosystemLoan1: String
    val aboutEcosystemLoan2: String
    val aboutEcosystemLoan3: String
    val aboutEcosystemLoan4: String
    val aboutEcosystemLoan5: String
    val aboutEcosystemLoan6: String
    val aboutEcosystemLoan7: String

    // About Classic savings
    val aboutClassicSavingsTitle: String
    val aboutClassicAccount: String
    val aboutClassicInterestTitle: String
    val aboutClassicInterestRateDesc1: String
    val aboutClassicAccountRateDesc2: String
    val aboutClassicInterestInformation: String
    val whatShouldYouGetAccount: String
    val whatShouldYouGetClassicAccountDesc: String
    val aboutClassicBonus: String
    val whatYouNeedClassicAccount: String
    val whatYouNeedClassicAccountDesc: String
    val aboutClassicWithdrawals: String
    val aboutClassicWithdrawDesc1: String
    val aboutClassicAccountWithdraw3: String
    val aboutClassicAccountWithdraw4: String

    // About Call Deposit
    val aboutCallDepositTitle: String
    val aboutCallDepositDesc: String
    val aboutCallDepositInterest: String
    val aboutCallDepositInformation: String
    val aboutCallBenefit: String
    val idealAccountCall: String
    val callDepositIdealDesc: String
    val whatYouNeedCallDepositTitle: String
    val whatYouNeedCallDeposit: String
    val callDepositTopAndWithdrawTitle: String
    val callDepositTopAndWithdraw: String
    val callDepositAccountClosure: String
    val callDepositAccountClosureDesc: String

    // About Fixed Deposit
    val aboutFixedAccount: String
    val aboutFixedAccountDesc: String
    val aboutFixedDepositInterest: String
    val aboutFixedDepositDesc: String
    val aboutFixedDepositInformation: String
    val aboutFixedShouldYouAccount: String
    val aboutFixedShouldYouThisAccountDesc: String
    val aboutWhatDoNeedToOpenHint: String
    val aboutWhatDoNeedToOpenDesc: String
    val fixedWithdrawal: String


    // About Goal savings
    val aboutGoalSavingsTitle: String
    val aboutGoalAccount: String
    val goalInterestTitle: String
    val aboutGoalInterestRate: String
    val aboutGoalAccountBenefit: String
    val aboutGoalAccountIdeal: String
    val aboutGoalAccountIdealDesc: String
    val aboutGoalAccountWhatYouNeed: String
    val aboutGoalAccountWhatYouNeedDescription: String
    val aboutGoalAccountTopUpAndWithdraw: String
    val aboutGoalAccountTopUpAndWithdrawDesc: String
    val aboutGoalAccountAccountClosure: String
    val aboutGoalAccountAccountClosureDesc: String

    // Get in Touch
    val contactUs: String
    val equityContact: String
    val emailUs: String
    val equityEmail: String
    val website: String
    val equityWebsite: String
    val twitter: String
    val equityTwitter: String
    val facebook: String
    val equityFacebook: String
    val linkedin: String
    val equityLinkedin: String

    // Manage Devices
    val mobileDevice: String
    val noOfMobileDevices: String
    val webDevices: String
    val webDevicesNo: String
    val getInTouchDesc: String
    val whichDeviceWouldYouLikeToRemove: String
    val mobileDevicesDesc: String
    val changeYourPin: String
    val changeYourExistingPin: String
    val resetYourPin: String
    val resetYourPinIfYouVeForgottenIt: String
    val makeSureYourPinEasy: String
    val enterCurrentPin: String
    val enterNewPin: String
    val newPin: String
    val currentPin: String
    val confirmNewPassword: String
    val newPassword: String
    val currentPassword: String

    // Notifications
    val selectTheAccountYouWantToGetTransactionAlertFor: String
    val howDoYouWantToReceiveYourAlerts: String
    val notificationDisabled: String
    val smsAlert: String
    val alertEnabled: String
    val enableAllAccounts: String
    val notificationEnabled: String
    val selectTheAccountYouWantToGetRemindersAlertFor: String
    val howDoYouWantToReceiveYourNotification: String
    val emailNotification: String
    val pushNotification: String
    val accountUser: String
    val accountNumber: String
    val buyForSomeoneNew: String
    val searchForCountry: String
    val getInTouchSubtitle: String
    val makePayment: String
    val sendToSomeoneNew: String
    val enterAnAccountNumber: String
    val withdrawFromPaypal: String
    val withdrawCash: String
    val sendMoney: String
    val westernUnionSendMoneySubtitle: String
    val receiveMoney: String
    val westernUnionReceiveMoneySubtitle: String
    val signInWithTouchId: String
    val recommend: String
    val activateChatBanking: String
    val activateChatBankingDesc: String
    val addAnEquityAccount: String
    val addAnEquityAccountDes: String
    val addYourPaypalAccountDesc: String
    val darkMode: String
}


